use clap::Parser;

/// `SpelLSP` a spellchecking LSP for any language
#[derive(Parser, Debug, Clone)]
#[command(version, about)]
pub struct Args {
    /// Select what language to use for spellchecking and lookups
    #[arg(short, long, value_enum, default_value_t = Language::En)]
    pub lang: Language,
}

impl Language {
    pub fn wooorm_dictionary_github_root(self) -> String {
        let lang_string = self.into_wooorm_dictionary_lang_str();
        format!(
            "https://raw.githubusercontent.com/wooorm/dictionaries/refs/heads/main/dictionaries/{lang_string}"
        )
    }
    pub fn into_wooorm_dictionary_lang_str(self) -> &'static str {
        match self {
            Language::En => "en",
            Language::Ru => "ru",
            Language::Bg => "bg",
            Language::Br => "br",
            Language::Ca => "ca",
            Language::CaValencia => "ca-valencia",
            Language::Cs => "cs",
            Language::Cy => "cy",
            Language::Da => "da",
            Language::De => "de",
            Language::DeAt => "de-AT",
            Language::DeCh => "de-CH",
            Language::El => "el",
            Language::ElPolyton => "el-polyton",
            Language::EnGb => "en-GB",
            Language::EnAu => "en-AU",
            Language::EnCa => "en-CA",
            Language::Eo => "eo",
            Language::Es => "es",
            Language::EsAr => "es-AR",
            Language::EsBo => "es-BO",
            Language::EsCl => "es-CL",
            Language::EsCo => "es-CO",
            Language::EsCr => "es-CR",
            Language::EsCu => "es-CU",
            Language::EsDo => "es-DO",
            Language::EsEc => "es-EC",
            Language::EsGt => "es-GT",
            Language::EsHn => "es-HN",
            Language::EsMx => "es-MX",
            Language::EsNi => "es-NI",
            Language::EsPa => "es-PA",
            Language::EsPe => "es-PE",
            Language::EsPh => "es-PH",
            Language::EsPr => "es-PR",
            Language::EsPy => "es-PY",
            Language::EsSv => "es-SV",
            Language::EsUs => "es-US",
            Language::EsUy => "es-UY",
            Language::EsVe => "es-VE",
            Language::Et => "et",
            Language::Eu => "eu",
            Language::Fa => "fa",
            Language::Fo => "fo",
            Language::Fr => "fr",
            Language::Fur => "fur",
            Language::Fy => "fy",
            Language::Ga => "ga",
            Language::Gd => "gd",
            Language::Gl => "gl",
            Language::He => "he",
            Language::Hr => "hr",
            Language::Hu => "hu",
            Language::Hy => "hy",
            Language::Hyw => "hyw",
            Language::Ia => "ia",
            Language::Ie => "ie",
            Language::Is => "is",
            Language::It => "it",
            Language::Ka => "ka",
            Language::Ko => "ko",
            Language::La => "la",
            Language::Lb => "lb",
            Language::Lt => "lt",
            Language::Ltg => "ltg",
            Language::Lv => "lv",
            Language::Mk => "mk",
            Language::Mn => "mn",
            Language::Nb => "nb",
            Language::Nds => "nds",
            Language::Ne => "ne",
            Language::Nl => "nl",
            Language::Nn => "nn",
            Language::Oc => "oc",
            Language::Pl => "pl",
            Language::Pt => "pt",
            Language::PtPt => "pt-PT",
            Language::Ro => "ro",
            Language::Rw => "rw",
            Language::Sk => "sk",
            Language::Sl => "sl",
            Language::Sr => "sr",
            Language::SrLatn => "sr-Latn",
            Language::Sv => "sv",
            Language::SvFi => "sv-FI",
            Language::Tk => "tk",
            Language::Tlh => "tlh",
            Language::TlhLatn => "tlh-Latn",
            Language::Tr => "tr",
            Language::Uk => "uk",
            Language::Vi => "vi",
        }
    }
}
#[derive(clap::ValueEnum, Debug, Clone, Copy)]
#[clap(rename_all = "kebab_case")]
pub enum Language {
    // TODO: HOW THE FUCK DO I ADD DOCUMENTATION TO THIS NOTHING DISPLAYS IN THE CLI THIS IS SO ANNOYING THERE IS LIKE NO INFO ABOUT THIS
    Bg,
    Br,
    Ca,
    CaValencia,
    Cs,
    Cy,
    Da,
    De,
    DeAt,
    DeCh,
    El,
    ElPolyton,
    En,
    EnGb,
    EnAu,
    EnCa,
    Eo,
    Es,
    EsAr,
    EsBo,
    EsCl,
    EsCo,
    EsCr,
    EsCu,
    EsDo,
    EsEc,
    EsGt,
    EsHn,
    EsMx,
    EsNi,
    EsPa,
    EsPe,
    EsPh,
    EsPr,
    EsPy,
    EsSv,
    EsUs,
    EsUy,
    EsVe,
    Et,
    Eu,
    Fa,
    Fo,
    Fr,
    Fur,
    Fy,
    Ga,
    Gd,
    Gl,
    He,
    Hr,
    Hu,
    Hy,
    Hyw,
    Ia,
    Ie,
    Is,
    It,
    Ka,
    Ko,
    La,
    Lb,
    Lt,
    Ltg,
    Lv,
    Mk,
    Mn,
    Nb,
    Nds,
    Ne,
    Nl,
    Nn,
    Oc,
    Pl,
    Pt,
    PtPt,
    Ro,
    Ru,
    Rw,
    Sk,
    Sl,
    Sr,
    SrLatn,
    Sv,
    SvFi,
    Tk,
    Tlh,
    TlhLatn,
    Tr,
    Uk,
    Vi,
}
